Repository essential-contributions/pint, pull requests merged in 2024-11, with the labels that each got.

#964 Allow, in the parser, maps to have arrays as keys by handling the token `[[`
  pintc/src/pint_parser.lalrpop
  pintc/tests/arrays/double_bracket.pnt
Labels: compiler :dragon: : parser

#969 Fix macros and `let`.
  pintc/src/macros.rs
  pintc/src/parser/context.rs
  pintc/src/pint_parser.lalrpop
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/variables.rs
  pintc/tests/macros/bad_splicing.pnt
  pintc/tests/macros/hygiene.pnt
  pintc/tests/macros/splicing_expression_size.pnt
  pintc/tests/macros/splicing_simple.pnt
Labels: bug :bug:, compiler :dragon: : parser

#971 Small `macro` updates to the book
  docs/book/src/advanced/macros.md
  examples/macros_1.pnt
  examples/macros_2.pnt
  examples/macros_3.pnt
Labels: The Book of Pint

#965 Add more `pint` printing flags
  Cargo.lock
  docs/book/src/pint-reference/cli.md
  pint-abi-gen-tests/build.rs
  pint-cli/src/build.rs
  pint-manifest/src/lib.rs
  pint-pkg/Cargo.toml
  pint-pkg/src/build.rs
  pint-pkg/tests/build.rs
Labels: pint :toolbox:

#953 Allow accessing `storage maps` in `tuples`
  examples/storage_dynamic_b.pnt
  pint-abi-gen-tests/src/exhaustive_storage.rs
  pint-abi-gen-tests/src/lib.rs
  pint-abi-gen-tests/test-pkgs/exhaustive_storage/.gitignore
  pint-abi-gen-tests/test-pkgs/exhaustive_storage/pint.toml
  pint-abi-gen-tests/test-pkgs/exhaustive_storage/src/contract.pnt
  pint-abi-gen-tests/tests/exhaustive_storage.rs
  pintc/src/predicate/analyse/type_check/validate.rs
  pintc/src/types.rs
  pintc/tests/arrays/double_bracket.pnt
  pintc/tests/storage/bad_storage_types.pnt
  pintc/tests/storage/storage_map_keys.pnt
  tests/validation_tests/storage_map_keys.pnt
  tests/validation_tests/storage_map_keys.toml
  tests/validation_tests/storage_maps_in_tuples.pnt
  tests/validation_tests/storage_maps_in_tuples.toml
Labels: bug :bug:

#968 Abi Gen Docs in the Book of Pint
  Cargo.lock
  docs/book/src/SUMMARY.md
  docs/book/src/appendix/abi/abi_gen.md
  docs/book/src/appendix/abi/abi_spec.md
  docs/book/src/appendix/abi/index.md
  examples/Cargo.toml
  examples/abi_gen_example.rs
  examples/abi_gen_example/.gitignore
  examples/abi_gen_example/out/debug/abi_gen_example-abi.json
  examples/abi_gen_example/out/debug/abi_gen_example.json
  examples/abi_gen_example/pint.toml
  examples/abi_gen_example/src/contract.pnt
  examples/util.rs
  pint-abi-gen/src/lib.rs
  pint-pkg/src/build.rs
Labels: The Book of Pint

#977 Bump pintc to `0.8.0`
  Cargo.lock
  Cargo.toml
  pint-abi-gen/Cargo.toml
  pint-abi/Cargo.toml
  pint-cli/Cargo.toml
  pint-pkg/Cargo.toml
  pintc/Cargo.toml
Labels: release

#989 Update interface and predicate instance syntax
  docs/book/src/advanced/invoking_predicates.md
  docs/book/src/storage/external.md
  examples/invoking_predicates_2.pnt
  examples/invoking_predicates_3.pnt
  examples/invoking_predicates_4.pnt
  examples/storage_external.pnt
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/external_calls.rs
  pintc/src/asm_gen/tests/multi_predicates.rs
  pintc/src/expr/display.rs
  pintc/src/lexer.rs
  pintc/src/lexer/tests.rs
  pintc/src/parser/tests.rs
  pintc/src/pint_parser.lalrpop
  pintc/tests/asm/simple_db.pnt
  pintc/tests/basic_tests/predicate_calls.pnt
  pintc/tests/consts/const_addr.pnt
  pintc/tests/consts/instance_address.pnt
  pintc/tests/consts/interface_address.pnt
  pintc/tests/evaluator/simple.pnt
  pintc/tests/interfaces/bad_address.pnt
  pintc/tests/interfaces/bad_interfaces.pnt
  pintc/tests/interfaces/bad_predicate_instances.pnt
  pintc/tests/interfaces/cycle1.pnt
  pintc/tests/interfaces/local_predicate.pnt
  pintc/tests/interfaces/simple.pnt
  pintc/tests/intrinsics/vec_len.pnt
  pintc/tests/macros/bad_splicing.pnt
  pintc/tests/macros/splicing_expression_size.pnt
  pintc/tests/root_types/exprs.pnt
  pintc/tests/root_types/interfaces.pnt
  pintc/tests/storage/bad_storage_accesses.pnt
  pintc/tests/storage/external_storage/main.pnt
  pintc/tests/storage/missing_extern.pnt
  pintc/tests/storage/storage_array.pnt
  pintc/tests/storage/storage_tuple.pnt
  pintc/tests/storage/storage_vector.pnt
  pintc/tests/types/bad_array_range_expr.pnt
  pintc/tests/types/recursive_array_vars.pnt
  tests/validation_tests/external_access.pnt
  tests/validation_tests/multi_external.pnt
  tests/validation_tests/predicate_call.pnt
  tests/validation_tests/simple_db.pnt
  tests/validation_tests/storage_array.pnt
  tests/validation_tests/storage_array_of_tuples.pnt
  tests/validation_tests/storage_tuple.pnt
  tests/validation_tests/storage_vector.pnt
  tests/validation_tests/transient_extern_same_contract.pnt
  tests/validation_tests/transient_external.pnt
Labels: compiler :dragon: : parser, The Book of Pint

#990 bump `pintc` to `0.9.0`
  Cargo.lock
  Cargo.toml
  pint-abi-gen/Cargo.toml
  pint-abi/Cargo.toml
  pint-cli/Cargo.toml
  pint-pkg/Cargo.toml
  pintc/Cargo.toml
Labels: release

#996 Document storage keys assignment in the Book of Pint
  docs/book/src/SUMMARY.md
  docs/book/src/appendix/abi/abi_gen.md
  docs/book/src/appendix/known_issues.md
  docs/book/src/appendix/storage_keys.md
Labels: The Book of Pint

#998 Bump pintc to `0.10.0`
  Cargo.lock
  Cargo.toml
  pint-abi-gen/Cargo.toml
  pint-abi/Cargo.toml
  pint-cli/Cargo.toml
  pint-pkg/Cargo.toml
  pintc/Cargo.toml
Labels: release

#999 Bump `pintc` to `0.11.0`
  Cargo.lock
  Cargo.toml
  pint-abi-gen/Cargo.toml
  pint-abi/Cargo.toml
  pint-cli/Cargo.toml
  pint-pkg/Cargo.toml
  pintc/Cargo.toml
Labels: release

#1000 Refactor internal errors
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/error.rs
  pintc/src/error/compile_error.rs
  pintc/src/error/handler.rs
  pintc/src/expr/evaluate.rs
  pintc/src/macros.rs
  pintc/src/parser.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check/check_exprs.rs
  pintc/src/predicate/analyse/type_check/check_paths.rs
  pintc/src/predicate/analyse/type_check/custom_types.rs
  pintc/src/predicate/optimize/const_folding.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/src/predicate/transform/unroll.rs
  pintc/src/predicate/transform/validate.rs
  pintc/src/types.rs
Labels: code quality 🤓

#1004 Fix alias in union variant resolution
  pintc/src/predicate/analyse/type_check/check_exprs.rs
  pintc/src/predicate/analyse/type_check/custom_types.rs
  pintc/src/predicate/transform/lower.rs
  pintc/tests/unions/alias.pnt
Labels: bug :bug:, compiler :dragon: : semantic analysis

#1005 Disallow multiple identical predicates in the same contract
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/multi_predicates.rs
  pintc/src/error/compile_error.rs
  pintc/src/expr.rs
  pintc/src/parser/tests.rs
  pintc/src/pint_parser.lalrpop
  pintc/src/predicate.rs
  pintc/src/predicate/analyse/type_check/check_decls.rs
  pintc/src/predicate/analyse/type_check/check_exprs.rs
Labels: bug :bug:

#1006 Add most of fixed size array map morphisms.
  pint-abi-gen-tests/test-pkgs/unions/src/contract.pnt
  pint-abi-gen-tests/tests/unions.rs
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/error/compile_error.rs
  pintc/src/error/handler.rs
  pintc/src/expr.rs
  pintc/src/expr/display.rs
  pintc/src/expr/evaluate.rs
  pintc/src/lexer.rs
  pintc/src/lexer/tests.rs
  pintc/src/macros.rs
  pintc/src/parser.rs
  pintc/src/parser/tests.rs
  pintc/src/pint_parser.lalrpop
  pintc/src/predicate.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check/check_exprs.rs
  pintc/src/predicate/analyse/type_check/check_paths.rs
  pintc/src/predicate/analyse/type_check/custom_types.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/optimize/const_folding.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/src/predicate/transform/unroll.rs
  pintc/src/predicate/transform/validate.rs
  pintc/src/types.rs
  pintc/tests/loops/map_bad_type.pnt
  pintc/tests/loops/map_fixed_simple.pnt
  pintc/tests/macros/bad_splicing.pnt
  pintc/tests/macros/splicing_expression_size.pnt
  pintc/tests/optimizations/dead_state_elimination.pnt
  pintc/tests/storage/bad_storage_accesses.pnt
  pintc/tests/storage/external_storage/lib.pnt
  pintc/tests/storage/external_storage/main.pnt
  pintc/tests/storage/mut_storage.pnt
  pintc/tests/tests.rs
  tests/validation_tests/complex_storage.pnt
  tests/validation_tests/external_access.pnt
Labels: enhancement, compiler :dragon: : parser, compiler :dragon: : asm backend, compiler :dragon: : semantic analysis

#1009 Add type checks to `const` initialisers.
  pintc/src/error/handler.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check/check_exprs.rs
  pintc/tests/consts/het_array.pnt
  pintc/tests/consts/type_check.pnt
  pintc/tests/evaluator/cast_error.pnt
  pintc/tests/evaluator/in_exprs.pnt
  pintc/tests/evaluator/select_error.pnt
  pintc/tests/evaluator/tuple_access_error_0.pnt
  pintc/tests/evaluator/tuple_access_error_1.pnt
  pintc/tests/experimental/cast_error.pnt
Labels: bug :bug:, compiler :dragon: : semantic analysis

#1010 Change handler to emit only a single error per span.
  pintc/src/error/handler.rs
  pintc/src/predicate/transform/validate.rs
  pintc/src/span.rs
  pintc/tests/arrays/non_const_index.pnt
  pintc/tests/arrays/out_of_bounds_index.pnt
  pintc/tests/arrays/out_of_bounds_index_multidimensional.pnt
  pintc/tests/arrays/out_of_bounds_index_multidimensional_second.pnt
  pintc/tests/consts/index_out_of_bounds.pnt
  pintc/tests/consts/type_check.pnt
  pintc/tests/evaluator/cast_error.pnt
  pintc/tests/evaluator/index_error_0.pnt
  pintc/tests/evaluator/index_error_1.pnt
  pintc/tests/evaluator/tuple_access_error_0.pnt
  pintc/tests/evaluator/tuple_access_error_1.pnt
  pintc/tests/experimental/cast_error.pnt
  pintc/tests/generators/generator_type_errors.pnt
  pintc/tests/interfaces/bad_address.pnt
  pintc/tests/modules/07/main.pnt
  pintc/tests/types/empty_array.pnt
  pintc/tests/types/new_type_recursion.pnt
  pintc/tests/types/new_type_unknown.pnt
  pintc/tests/types/recursive_array_vars.pnt
  pintc/tests/types/undefined_types.pnt
  pintc/tests/unions/unknown_union.pnt
Labels: enhancement, compiler :dragon: : semantic analysis

#1011 `Fold` known `let` variables
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/external_calls.rs
  pintc/src/predicate/optimize/const_folding.rs
  pintc/tests/optimizations/const_folding_lets.pnt
  pintc/tests/optimizations/dead_state_elimination.pnt
  pintc/tests/storage/bad_storage_accesses.pnt
  pintc/tests/storage/external_storage/main.pnt
  pintc/tests/storage/mut_storage.pnt
  tests/validation_tests/external_access.solution.json
  tests/validation_tests/multi_external.solution.json
  tests/validation_tests/predicate_call.solution.json
  tests/validation_tests/storage_array.solution.json
  tests/validation_tests/storage_array_of_tuples.solution.json
  tests/validation_tests/storage_tuple.solution.json
  tests/validation_tests/storage_vector.solution.json
Labels: optimization :chart_with_upwards_trend:
