Repository essential-contributions/pint, pull requests merged in 2024-09, with the labels that each got.

#866 Update README.md
  README.md
Labels: documentation :scroll:

#865 Emit `warnings`
  pint-cli/src/build.rs
  pint-pkg/src/build.rs
  pint-pkg/tests/build.rs
  pintc/src/error/handler.rs
  pintc/src/lib.rs
  pintc/src/main.rs
  pintc/src/parser.rs
  pintc/src/parser/tests.rs
  pintc/src/predicate.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/optimize.rs
  pintc/src/predicate/optimize/dead_code_elimination.rs
  pintc/src/predicate/transform/validate.rs
  pintc/src/warning.rs
  pintc/tests/experimental/dead_constraint_elimination.pnt
  pintc/tests/optimizations/dead_constraint_elimination.pnt
  pintc/tests/optimizations/dead_state_elimination.pnt
  pintc/tests/optimizations/false_constraint_simplification.pnt
  pintc/tests/tests.rs
  test-util/src/lib.rs
Labels: compiler :dragon: : ui

#867 More work on intrinsics and asm gen
  Cargo.lock
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/intrinsics.rs
  pintc/src/asm_gen/tests/multi_predicates.rs
  pintc/src/asm_gen/tests/pub_vars.rs
  pintc/src/expr/intrinsics.rs
  pintc/src/predicate/transform.rs
  pintc/src/predicate/transform/lower/lower_pub_var_accesses.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/src/types.rs
  pintc/tests/basic_tests/pub_vars.pnt
  pintc/tests/basic_tests/pub_vars_external_flattened.pnt
  pintc/tests/basic_tests/pub_vars_flattened.pnt
  pintc/tests/consts/instance_address.pnt
  pintc/tests/interfaces/local_predicate.pnt
  pintc/tests/interfaces/simple.pnt
  pintc/tests/tests.rs
  pintc/tests/types/new_type.pnt
  tests/validation_tests.rs
  tests/validation_tests/intrinsics.pnt
Labels: code quality 🤓

#872 Add front-end support for unions and `match` expressions and declarations.
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/error/compile_error.rs
  pintc/src/expr.rs
  pintc/src/expr/display.rs
  pintc/src/expr/evaluate.rs
  pintc/src/lexer.rs
  pintc/src/lexer/tests.rs
  pintc/src/parser/context.rs
  pintc/src/parser/tests.rs
  pintc/src/pint_parser.lalrpop
  pintc/src/predicate.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/src/predicate/display.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/states.rs
  pintc/src/predicate/transform.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/transform/unroll.rs
  pintc/src/predicate/transform/validate.rs
  pintc/src/predicate/vars.rs
  pintc/src/types.rs
  pintc/src/types/display.rs
  pintc/src/warning.rs
  pintc/tests/consts/bad_pos.pnt
  pintc/tests/contracts/bad_stateful.pnt
  pintc/tests/macros/bad_splicing.pnt
  pintc/tests/macros/splicing_expression_size.pnt
  pintc/tests/test.pnt
  pintc/tests/tests.rs
  pintc/tests/unions/bad_match_name.pnt
  pintc/tests/unions/bad_match_value.pnt
  pintc/tests/unions/match_bindings_are_n.pnt
  pintc/tests/unions/match_decls.pnt
  pintc/tests/unions/match_else_extra.pnt
  pintc/tests/unions/match_else_reused.pnt
  pintc/tests/unions/match_non_union.pnt
  pintc/tests/unions/match_too_few.pnt
  pintc/tests/unions/name_clash.pnt
  pintc/tests/unions/no_value_union.pnt
  pintc/tests/unions/simple.pnt
  pintc/tests/unions/unknown_union.pnt
  pintc/tests/unions/variant_hint.pnt
Labels: enhancement

#884 *WIP: Optimize `Selects`
  pintc/src/asm_gen/tests.rs
  pintc/src/predicate/optimize/dead_code_elimination.rs
  pintc/src/warning.rs
  pintc/tests/optimizations/dead_select_elimination.pnt
  pintc/tests/optimizations/dead_state_elimination.pnt
Labels: optimization :chart_with_upwards_trend:

#887 Lift the union tag comparisons up into transforms rather than in ASM gen.
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/expr.rs
  pintc/src/expr/display.rs
  pintc/src/expr/evaluate.rs
  pintc/src/predicate.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/transform/validate.rs
  pintc/src/types.rs
  pintc/tests/unions/match_bindings_are_n.pnt
  pintc/tests/unions/match_decls.pnt
  pintc/tests/unions/no_value_union.pnt
  pintc/tests/unions/simple.pnt
Labels: compiler :dragon: : semantic analysis

#889 Keep track of `span` when `lowering ifs`
  pintc/src/predicate/transform/lower.rs
  pintc/tests/optimizations/false_constraint_simplification.pnt
Labels: bug :bug:, compiler :dragon: : ui

#890 Remove `warning` for constraints that are always positive
  pintc/src/predicate/optimize/dead_code_elimination.rs
  pintc/src/warning.rs
  pintc/tests/experimental/dead_constraint_elimination.pnt
  pintc/tests/optimizations/dead_constraint_elimination.pnt
Labels: compiler :dragon: : ui

#888 Further adventures in enum lowering.
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/expr.rs
  pintc/src/expr/display.rs
  pintc/src/expr/evaluate.rs
  pintc/src/predicate/analyse/array_check.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/types.rs
  pintc/tests/consts/simple.pnt
  pintc/tests/types/const_tuples_with_enums.pnt
  pintc/tests/types/nested_enums.pnt
  pintc/tests/types/new_type.pnt
  pintc/tests/unions/simple.pnt
Labels: bug :bug:, compiler :dragon: : semantic analysis

#893 Disallow `==` or `!=` comparisons for union variant.
  pintc/src/error/compile_error.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/tests/basic_tests/bad_nil.pnt
  pintc/tests/basic_tests/if_statement_body_type_error.pnt
  pintc/tests/interfaces/bad_address.pnt
  pintc/tests/types/binary_ops.pnt
  pintc/tests/unions/bad_conditional.pnt
  pintc/tests/unions/no_value_union.pnt
  pintc/tests/unions/simple.pnt
Labels: compiler :dragon: : semantic analysis

#895 Split `type_check.rs` into smaller modules.
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/src/predicate/analyse/type_check/check_decls.rs
  pintc/src/predicate/analyse/type_check/check_exprs.rs
  pintc/src/predicate/analyse/type_check/check_paths.rs
  pintc/src/predicate/analyse/type_check/custom_types.rs
  pintc/src/predicate/analyse/type_check/validate.rs
Labels: code quality 🤓

#896 Re-enable some `<disabled>` E2E tests.
  pintc/src/predicate.rs
  pintc/src/predicate/transform/lower.rs
  pintc/tests/consts/simple.pnt
  pintc/tests/root_types/consts.pnt
  pintc/tests/root_types/interfaces.pnt
Labels: testing :test_tube:

#897 Improve ASM gen for unions.
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/predicate/analyse/type_check/check_exprs.rs
  pintc/src/types.rs
  pintc/tests/unions/bad_conditional.pnt
  pintc/tests/unions/no_value_union.pnt
  pintc/tests/unions/simple.pnt
  tests/validation_tests/union_compare.pnt
  tests/validation_tests/union_compare.toml
  tests/validation_tests/union_matches.pnt
  tests/validation_tests/union_matches.toml
Labels: compiler :dragon: : asm backend

#900 Fix minor typos in book
  docs/book/src/projects/modules.md
Labels: documentation :scroll:
