Repository essential-contributions/pint, pull requests merged in 2024-12, with the labels that each got.

#1023 Fix for Rust v1.83.0.
  .github/workflows/ci.yml
  .github/workflows/mdbook.yml
  pint-solve/src/lib.rs
  pint-solve/src/scip.rs
  pint-solve/src/scip/constraint.rs
  pint-solve/src/scip/invert.rs
  pint-solve/src/scip/print.rs
  pint-solve/src/scip/variable.rs
  pintc/src/lexer.rs
  pintc/src/parser.rs
  pintc/src/parser/tests.rs
  pintc/src/parser/use_path.rs
  pintc/src/predicate.rs
  pintc/src/predicate/display.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/variables.rs
  pintc/src/util.rs
Labels: code quality 🤓

#1027 Perform a `cargo update`.
  Cargo.lock
Labels: dependencies

#1026 Print content addresses when compiling with `pintc`
  pintc/src/main.rs
  pintc/tests/cli.rs
Labels: compiler :dragon: : ui

#1029 Change the strictness around shadowing for match bindings.
  pintc/src/main.rs
  pintc/src/pint_parser.lalrpop
  pintc/src/predicate.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check/check_paths.rs
  pintc/src/predicate/analyse/type_check/validate.rs
  pintc/src/predicate/transform/lower.rs
  pintc/tests/arrays/compare_different_sizes.pnt
  pintc/tests/cli.rs
  pintc/tests/consts/bad_type.pnt
  pintc/tests/consts/const_addr.pnt
  pintc/tests/consts/dependent.pnt
  pintc/tests/consts/if_decl.pnt
  pintc/tests/consts/instance_address.pnt
  pintc/tests/consts/module_sets/main.pnt
  pintc/tests/consts/simple.pnt
  pintc/tests/consts/type_check.pnt
  pintc/tests/evaluator/cast_error.pnt
  pintc/tests/evaluator/in_exprs.pnt
  pintc/tests/experimental/cast_error.pnt
  pintc/tests/experimental/in_expr_evaluation.pnt
  pintc/tests/optimizations/const_folding.pnt
  pintc/tests/optimizations/dead_constraint_elimination.pnt
  pintc/tests/root_types/consts.pnt
  pintc/tests/types/undefined_types.pnt
  pintc/tests/unions/const_eval.pnt
  pintc/tests/unions/match_bindings_are_n.pnt
  pintc/tests/unions/shadowing.pnt
  tests/validation_tests/union_compare.pnt
Labels: bug :bug:, compiler :dragon: : semantic analysis

#1031 bump `pintc` to `0.12.0`
  Cargo.lock
  Cargo.toml
  pint-abi-gen/Cargo.toml
  pint-abi-visit/Cargo.toml
  pint-abi/Cargo.toml
  pint-cli/Cargo.toml
  pint-pkg/Cargo.toml
  pint-solve/Cargo.toml
  pintc/Cargo.toml
  pintfmt/Cargo.toml
Labels: release

#1036 Wrong type for next state tuple field access
  pintc/src/asm_gen/asm_builder.rs
  pintc/tests/storage/tuple_field_access_primes.pnt
Labels: bug :bug:

#1038 Minor refactor of asm gen
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/external_calls.rs
  pintc/src/asm_gen/tests/intrinsics.rs
  pintc/src/expr.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/src/types.rs
Labels: compiler :dragon: : asm backend
