Repository essential-contributions/pint, pull requests merged in 2024-08, with the labels that each got.

#816 Finalise predicate refactor.
  pintc/src/error/compile_error.rs
  pintc/src/expr/evaluate.rs
  pintc/src/parser.rs
  pintc/src/predicate.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/transform.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/transform/unroll.rs
  pintc/src/types.rs
  pintc/tests/consts/dependent.pnt
  pintc/tests/consts/index_out_of_bounds.pnt
  pintc/tests/consts/simple.pnt
  pintc/tests/evaluator/index_error_0.pnt
  pintc/tests/evaluator/index_error_1.pnt
  pintc/tests/evaluator/simple.pnt
  pintc/tests/root_types/arrays.pnt
  pintc/tests/root_types/consts.pnt
  pintc/tests/root_types/custom.pnt
  pintc/tests/root_types/exprs.pnt
  pintc/tests/root_types/interfaces.pnt
  pintc/tests/root_types/storage.pnt
Labels: code quality 🤓

#813 Disallow state variables from having types that contain storage types #805
  pintc/src/error/compile_error.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/tests/storage/invalid_state_var_storage_type.pnt
Labels: bug :bug:

#819 Ensure during macro expansion that spans don't 'span out' of the macro to the call site.
  pintc/src/macros.rs
  pintc/tests/macros/bad_splicing.pnt
  pintc/tests/macros/splicing_expression_size.pnt
  pintc/tests/regression/github_721.pnt
Labels: bug :bug:, compiler :dragon: : parser

#820 Assign `intrinsic` types even if malformed
  pintc/src/predicate/analyse/intrinsics.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/tests/intrinsics/bad_state_len_arg.pnt
  pintc/tests/intrinsics/incorrect_args.pnt
Labels: compiler :dragon: : ui

#826 Insert constraint on pathway addresses and refactor storage
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/tests/transient.rs
  pintc/src/predicate.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/transform.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/transform/lower/lower_pub_var_accesses.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/tests/basic_tests/pub_vars_external_flattened.pnt
  pintc/tests/basic_tests/pub_vars_flattened.pnt
  pintc/tests/consts/instance_address.pnt
  pintc/tests/interfaces/simple.pnt
Labels: code quality 🤓, flattening :flatbread:

#824 Cut down unnecessary errors from failed inferences
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/intrinsics.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/tests/arrays/bad_const_index.pnt
  pintc/tests/arrays/index_enum_with_int.pnt
  pintc/tests/arrays/index_int_with_enum.pnt
  pintc/tests/arrays/non_existent_array_access.pnt
  pintc/tests/basic_tests/bad_nil.pnt
  pintc/tests/basic_tests/mismatch_enums.pnt
  pintc/tests/consts/bad_type.pnt
  pintc/tests/generators/generator_type_errors.pnt
  pintc/tests/interfaces/bad_address.pnt
  pintc/tests/interfaces/bad_interfaces.pnt
  pintc/tests/regression/github_721.pnt
  pintc/tests/storage/invalid_next_state.pnt
  pintc/tests/storage/missing_extern.pnt
  pintc/tests/types/bad_in_expr.pnt
  pintc/tests/types/bad_tuple_name_index.pnt
  pintc/tests/types/bad_tuple_num_index.pnt
  pintc/tests/types/binary_ops.pnt
  pintc/tests/types/clashing_enums.pnt
  pintc/tests/types/empty_array.pnt
  pintc/tests/types/enum_variant_unqualified.pnt
  pintc/tests/types/heterogeneous_array.pnt
  pintc/tests/types/new_type_unknown.pnt
  pintc/tests/types/non_array_access.pnt
  pintc/tests/types/non_int_array_access.pnt
  pintc/tests/types/non_tuple_access.pnt
  pintc/tests/types/select_branches.pnt
  pintc/tests/types/select_cond.pnt
  pintc/tests/types/state_in_ops.pnt
  pintc/tests/types/unary_ops.pnt
Labels: compiler :dragon: : ui

#830 Reduce the error output from type checking a little bit more.
  pintc/src/error/compile_error.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/src/types.rs
  pintc/tests/arrays/bad_indexed_value.pnt
  pintc/tests/arrays/non_existent_array_access.pnt
  pintc/tests/basic_tests/bad_nil.pnt
  pintc/tests/regression/github_721.pnt
  pintc/tests/storage/invalid_next_state.pnt
  pintc/tests/storage/missing_extern.pnt
  pintc/tests/types/bad_in_expr.pnt
  pintc/tests/types/bad_tuple_name_index.pnt
  pintc/tests/types/bad_tuple_num_index.pnt
  pintc/tests/types/constraint_non_bool_types.pnt
  pintc/tests/types/recursive_array_vars.pnt
  pintc/tests/types/recursive_scalar_vars.pnt
Labels: code quality 🤓

#835 General refactor of intrinsics and asm_gen
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/error/compile_error.rs
  pintc/src/error/parse_error.rs
  pintc/src/expr.rs
  pintc/src/expr/display.rs
  pintc/src/expr/evaluate.rs
  pintc/src/expr/intrinsics.rs
  pintc/src/parser/context.rs
  pintc/src/parser/tests.rs
  pintc/src/pint_parser.lalrpop
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/intrinsics.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/src/predicate/transform/legalize.rs
  pintc/src/predicate/transform/lower.rs
  pintc/src/predicate/transform/lower/lower_pub_var_accesses.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/src/predicate/transform/validate.rs
  pintc/src/types.rs
  pintc/src/types/display.rs
  pintc/tests/arrays/bad_indexed_value.pnt
  pintc/tests/intrinsics/bad_state_len_arg.pnt
  pintc/tests/intrinsics/bad_vec_len_arg.pnt
  pintc/tests/intrinsics/incorrect_args.pnt
  pintc/tests/intrinsics/missing_intrinsics.pnt
  pintc/tests/modules/10/main.pnt
  tests/validation_tests/intrinsics.pnt
Labels: compiler :dragon: : parser, compiler :dragon: : asm backend, compiler :dragon: : semantic analysis, code quality 🤓

#833 Do not compile dead state decls
  pintc/src/asm_gen/tests.rs
  pintc/src/predicate/states.rs
  pintc/src/predicate/transform.rs
  pintc/src/predicate/transform/dead_code_elimination.rs
  pintc/tests/consts/interface_address.pnt
  pintc/tests/interfaces/simple.pnt
  pintc/tests/intrinsics/vec_len.pnt
  pintc/tests/storage/dead_state_elimination.pnt
  pintc/tests/storage/external_storage/main.pnt
  pintc/tests/storage/mut_storage.pnt
  pintc/tests/storage/storage_multi_intent.pnt
  pintc/tests/storage/storage_tuple.pnt
  pintc/tests/storage/storage_vector.pnt
  pintc/tests/types/new_type.pnt
Labels: flattening :flatbread:

#843 Adjust the order in which predicates are included in the final compiled contract
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/multi_predicates.rs
Labels: bug :bug:, compiler :dragon: : asm backend

#846 Add `__address_of` and `__predicate_at`
  docs/book/src/appendix/intrinsics.md
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/error/compile_error.rs
  pintc/src/expr/intrinsics.rs
  pintc/src/parser/context.rs
  pintc/src/predicate/analyse/type_check.rs
  pintc/src/predicate/transform/lower/lower_pub_var_accesses.rs
  pintc/src/types.rs
  pintc/tests/interfaces/local_predicate.pnt
  pintc/tests/intrinsics/access_intrinsics.pnt
  pintc/tests/intrinsics/bad_address_of.pnt
  pintc/tests/test.pnt
  tests/validation_tests/intrinsics.pnt
  tests/validation_tests/intrinsics.toml
Labels: compiler :dragon: : asm backend, compiler :dragon: : semantic analysis, The Book of Pint

#850 Document `mut` and sibling predicate access
  docs/book/src/advanced/pub_vars.md
  docs/book/src/appendix/keywords.md
  docs/book/src/basics/constants.md
  docs/book/src/examples/counter.md
  docs/book/src/examples/subcurrency.md
  docs/book/src/getting_started/installation.md
  docs/book/src/getting_started/quickstart.md
  docs/book/src/storage/external.md
  docs/book/src/storage/static.md
  examples/ch_1_2/src/contract.pnt
  examples/ch_3_7.pnt
  examples/ch_4_2_c.pnt
  examples/ch_5_1.pnt
  examples/ch_5_2_a.pnt
  examples/ch_5_2_b.pnt
  examples/ch_5_3.pnt
  examples/ch_7_1.pnt
  examples/ch_7_1_b.pnt
  examples/ch_7_1_c.pnt
  examples/counter.pnt
  examples/subcurrency.pnt
  pint-pkg/src/new.rs
  pint-pkg/tests/build.rs
Labels: pint :toolbox:

#851 Remove dead `constraints`
  examples/runner.rs
  pint-abi-gen-tests/build.rs
  pint-cli/src/build.rs
  pint-pkg/src/build.rs
  pint-pkg/tests/build.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/cli.rs
  pintc/src/main.rs
  pintc/src/predicate.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/optimize.rs
  pintc/src/predicate/optimize/dead_code_elimination.rs
  pintc/src/predicate/transform.rs
  pintc/src/predicate/transform/dead_code_elimination.rs
  pintc/tests/consts/interface_address.pnt
  pintc/tests/interfaces/simple.pnt
  pintc/tests/intrinsics/vec_len.pnt
  pintc/tests/optimizations/dead_constraint_elimination.pnt
  pintc/tests/optimizations/dead_state_elimination.pnt
  pintc/tests/optimizations/false_constraint_simplification.pnt
  pintc/tests/storage/external_storage/main.pnt
  pintc/tests/storage/mut_storage.pnt
  pintc/tests/storage/storage_multi_intent.pnt
  pintc/tests/storage/storage_tuple.pnt
  pintc/tests/tests.rs
  pintc/tests/types/new_type.pnt
  test-util/src/lib.rs
  tests/solver_tests.rs
  tests/validation_tests.rs
  tests/validation_tests/intrinsics.pnt
Labels: optimization :chart_with_upwards_trend:
