Repository essential-contributions/pint, pull requests merged in 2025-01, with the labels that each got.

#1044 Fix prime coalescing to also take care of the type of the next state op
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/predicate/transform/lower.rs
  tests/validation_tests/tuples_and_arrays.pnt
  tests/validation_tests/tuples_and_arrays.solution.json
Labels: bug :bug:, compiler :dragon: : semantic analysis

#1050 `cargo update`, `trunk upgrade`, and update Rust to 1.84
  .github/workflows/ci.yml
  .trunk/trunk.yaml
  Cargo.lock
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/parser/use_path.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/src/types.rs
  tests/validation_tests.rs
Labels: ci :robot:, dependencies

#1039 Allow storage accesses everywhere
  pintc/src/asm_gen.rs
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/storage_accesses.rs
  pintc/src/error/compile_error.rs
  pintc/src/expr.rs
  pintc/src/expr/intrinsics.rs
  pintc/src/pint_parser.lalrpop
  pintc/src/predicate.rs
  pintc/src/predicate/analyse.rs
  pintc/src/predicate/analyse/type_check/check_exprs.rs
  pintc/src/predicate/analyse/type_check/validate.rs
  pintc/src/predicate/exprs.rs
  pintc/src/predicate/transform/lower/lower_storage_accesses.rs
  pintc/tests/asm/simple_db.pnt
  pintc/tests/basic_tests/nil.pnt
  pintc/tests/consts/const_addr.pnt
  pintc/tests/consts/interface_address.pnt
  pintc/tests/experimental/new_type.pnt
  pintc/tests/interfaces/simple.pnt
  pintc/tests/intrinsics/size_of.pnt
  pintc/tests/intrinsics/vec_len.pnt
  pintc/tests/intrinsics/vec_len_in_constraints.pnt
  pintc/tests/optimizations/const_folding_lets.pnt
  pintc/tests/optimizations/dead_state_elimination.pnt
  pintc/tests/root_types/interfaces.pnt
  pintc/tests/root_types/storage.pnt
  pintc/tests/storage/bad_storage_accesses.pnt
  pintc/tests/storage/erc20.pnt
  pintc/tests/storage/external_storage/main.pnt
  pintc/tests/storage/indexing_primes.pnt
  pintc/tests/storage/invalid_next_state.pnt
  pintc/tests/storage/mut_storage.pnt
  pintc/tests/storage/new_types.pnt
  pintc/tests/storage/state_programs.pnt
  pintc/tests/storage/storage_accesses_as_const_error.pnt
  pintc/tests/storage/storage_array.pnt
  pintc/tests/storage/storage_multi_intent.pnt
  pintc/tests/storage/storage_tuple.pnt
  pintc/tests/storage/storage_vector.pnt
  pintc/tests/storage/tuple_field_access_primes.pnt
  pintc/tests/types/new_type.pnt
  pintc/tests/unions/alias.pnt
  tests/validation_tests/complex_storage.pnt
  tests/validation_tests/counter1.pnt
  tests/validation_tests/counter2.pnt
  tests/validation_tests/external_access.pnt
  tests/validation_tests/multi_external.pnt
  tests/validation_tests/nil.pnt
  tests/validation_tests/simple_db.pnt
  tests/validation_tests/state_programs.pnt
  tests/validation_tests/storage_array_of_tuples.pnt
  tests/validation_tests/storage_maps_in_tuples.pnt
  tests/validation_tests/storage_tuple.pnt
  tests/validation_tests/storage_vector.pnt
  tests/validation_tests/tuples_and_arrays.pnt
  tests/validation_tests/unions_in_storage.pnt
Labels: compiler :dragon: : parser, compiler :dragon: : asm backend, compiler :dragon: : semantic analysis, flattening :flatbread:

#1054 Upgrade some dependencies
  Cargo.lock
  Cargo.toml
Labels: dependencies

#1048 Optimize away identical `variable` and `constraint decls`
  pintc/src/asm_gen/tests.rs
  pintc/src/expr.rs
  pintc/src/expr/intrinsics.rs
  pintc/src/predicate/optimize/dead_code_elimination.rs
  pintc/tests/optimizations/const_folding.pnt
  pintc/tests/optimizations/const_folding_lets.pnt
  pintc/tests/optimizations/dead_constraint_elimination.pnt
  pintc/tests/optimizations/dead_state_elimination.pnt
  pintc/tests/optimizations/duplicate_constraint_elimination.pnt
  pintc/tests/optimizations/duplicate_variable_elimination.pnt
Labels: optimization :chart_with_upwards_trend:

#1042 Add ASM gen for a map over a fixed sized array of `int`s.
  pintc/src/asm_gen/asm_builder.rs
  pintc/src/asm_gen/display.rs
  pintc/src/asm_gen/tests.rs
  pintc/src/asm_gen/tests/external_calls.rs
  pintc/src/asm_gen/tests/intrinsics.rs
  pintc/src/asm_gen/tests/multi_predicates.rs
  pintc/src/asm_gen/tests/storage_accesses.rs
  pintc/tests/loops/map_fixed_expr.pnt
  pintc/tests/loops/map_fixed_memory.pnt
  pintc/tests/loops/map_fixed_memory_post.pnt
  pintc/tests/loops/map_fixed_param.pnt
  pintc/tests/loops/map_fixed_storage.pnt
  pintc/tests/loops/map_fixed_storage_post.pnt
  tests/validation_tests/map_fixed_expr.pnt
  tests/validation_tests/map_fixed_expr.solution.json
  tests/validation_tests/map_fixed_memory.pnt
  tests/validation_tests/map_fixed_memory.solution.json
  tests/validation_tests/map_fixed_pred.pnt
  tests/validation_tests/map_fixed_pred.solution.json
  tests/validation_tests/map_fixed_storage.pnt
  tests/validation_tests/map_fixed_storage.solution.json
Labels: compiler :dragon: : asm backend

#1055 Improve error if a `const` is used in a `predicate`
  pintc/src/error/parse_error.rs
  pintc/src/pint_parser.lalrpop
  pintc/tests/consts/bad_pos.pnt
Labels: compiler :dragon: : ui
